### ISSUE TITLE
hacmini.pkg 3.1.2 updates macOS12, SDXC is no longer valid.

### ISSUE THREAD

**Issue by dellffff** [osy/HaC-Mini#949] opened 2021-10-29 05:51 UTC
Use hacmini.pkg 3.1.2 to update macOS12, SDXC has failed, whether the author knows that SDXC is invalid, SDXC work requirements, can reduce my interface usage, because more devices need to be connected

**Comment by Simanias** [comment] 2021-11-08 11:02
@dellffff the AppleSDXC.kext is loaded, but there is nothing showing in Finder.
Maybe there's an issue with the USB mapping.

**Comment by qwe123cjl** [comment] 2021-11-09 10:22
My card reader is no longer available after upgrading macOS12, I look forward to the author’s fix

**Comment by osy** [comment] 2021-11-21 02:13
Duplicate of #613

**Closed by osy** 2021-11-21 02:13 UTC
Labels: duplicate
