### ISSUE TITLE
Stuck at PCI Configuration after update to HaC Mini v2.15

### ISSUE THREAD

**Issue by Xuemuyang** [osy/HaC-Mini#461] opened 2020-12-09 02:34 UTC
**Describe the bug**
Stuck at PCI Configuration after update to HaC Mini v2.15

**Expected behavior**
Launch Big Sur successfully

**Configuration**
- HaC Mini version : v2.15
- OSX version : 11.0.1
- NUC model : NUC8i7HVK
- Boot SSD model and protocol : Hikvison c2000pro 1TB NVMe
- Second SSD model and protocol : Lexar NM 610 250G NVMe
- First DIMM model : Kingston DDR4-2666 16GB
- Second DIMM model : Kingston DDR4-2666 16GB
- Display port(s) used : miniDP
- Display resolution(s) : 1080
- Any TB3 devices: no
- Any USB devices: no
- Any Wi-Fi/Bluetooth devices : BCM94352Z

**Modifications**

Sorry i don't know how to provide this because i can't launch

**Panic log**

![e294edf575d3d5367319c0707b3aff27](https://user-images.githubusercontent.com/25718776/101565690-888ca480-3a08-11eb-829e-4e11fbc423be.jpg)

**Comment by osy** [comment] 2020-12-09 03:45
Can you reset NVRAM?

**Comment by Xuemuyang** [comment] 2020-12-09 03:57
> Can you reset NVRAM?

Thank you for your prompt reply.It doesn’t work the first time, and then I reset NVRAM, it still doesn’t work.

**Comment by osy** [comment] 2020-12-09 04:06
Can you try booting with a single NVMe?

**Comment by keatliang2005** [comment] 2020-12-09 05:42
I have the same issue, tried reset NVRAM still stuck at same place 

Configuration

HaC Mini version : v2.15
OSX version : 11.0.1
NUC model : NUC8i7HVK
Boot SSD model and protocol : KINGSTON SKC2500M8250G
Second SSD model and protocol : none
First DIMM model : Kingston KHX2666C15S4/16G
Second DIMM model : none
Display port(s) used : mDP
Display resolution(s) : 2K
Any TB3 devices: no
Any USB devices: Dell monitor USB hub
Any Wi-Fi/Bluetooth devices : Original Intel Card

Here's my stuck page

![image](https://user-images.githubusercontent.com/473990/101589916-5721d200-3a24-11eb-9c90-34d047faf754.png)

**Comment by osy** [comment] 2020-12-09 05:48
Does v2.14 work for both of you?

**Comment by Xuemuyang** [comment] 2020-12-09 06:07
> Does v2.14 work for both of you?

v2.14 has no problem.

**Comment by Xuemuyang** [comment] 2020-12-09 06:09
> Can you try booting with a single NVMe?

I'll try it about 8 hours later.

**Comment by keatliang2005** [comment] 2020-12-09 06:22
> Does v2.14 work for both of you?

Revert back to 2.14 + @goodbest patched kext, that works well

**Comment by osy** [comment] 2020-12-09 15:37
Those of you experiencing this issue, can you look at the changelog at the list of changed drivers and, one by one, replace the driver with the older version until it boots and let me know which one was the cause?

**Comment by keatliang2005** [comment] 2020-12-10 03:01
@osy found the culprit kexts AppleALC, replacing AppleALC from v2.14 able to boot.

Here's new issue found:
from my immediate observation i lost my verbose boot, even i confirm from config.plist

![Screenshot 2020-12-10 at 10 58 24 AM](https://user-images.githubusercontent.com/473990/101715669-d8d23800-3ad6-11eb-8969-ce76aec5fc4e.png)

**Comment by osy** [comment] 2020-12-10 03:54
Can others confirm if this solves the issue for them as well?

**Comment by Xuemuyang** [comment] 2020-12-10 10:37
Sorry, I accidentally clicked close.

**Comment by Xuemuyang** [comment] 2020-12-10 10:41
> Can others confirm if this solves the issue for them as well? Test: https://github.com/osy/HaC-Mini/suites/1640109402/artifacts/30350487

Thank you,it works.

**Comment by Xuemuyang** [comment] 2020-12-10 10:43
> @osy found the culprit kexts AppleALC, replacing AppleALC from v2.14 able to boot.

Thanks for your contribution.

**Comment by keatliang2005** [comment] 2020-12-10 12:05
@osy i was wonder how to we get debug info on boot ?

i look into the Lilu + Apple ALC, does it need both on debug build to have the crash log produce ?

**Comment by goodbest** [comment] 2020-12-10 12:55
If the suspect cause is AppleALC, and it stuck at PCI (but mine device don't stuck),
I guess the most likely fatal change is here:
https://github.com/acidanthera/AppleALC/commit/3708e1ceabe590a8ea7a13f8d0447cbaaadecb49#
The change for key `IOProviderClass`  to value `IOHDACodecDevice`. (it's related to the HDAS->HDEF patch).

If you want to analyse this, you can use the following build (build between 1.5.4 and 1.5.5, without the above patch)to see if the stuck issue exists
https://github.com/dortania/build-repo/releases/download/AppleALC-05c055a/AppleALC-1.5.5-RELEASE.zip

**Comment by keatliang2005** [comment] 2020-12-10 14:29
> If the cause is AppleALC, and it stuck at PCI (but mine device don't stuck),
> I guess the most likely suspicious change is here:
> https://github.com/acidanthera/AppleALC/commit/3708e1ceabe590a8ea7a13f8d0447cbaaadecb49#
> The change for key `IOProviderClass`  to value `IOHDACodecDevice`. (it's related to the HDAS->HDEF patch).
> 
> If you want to dive deep into this issue, you can use the following build (build between 1.5.4 and 1.5.5, without the above commit in `IOProviderClass`)to see if the stuck issue exists.
> https://github.com/dortania/build-repo/releases/download/AppleALC-05c055a/AppleALC-1.5.5-RELEASE.zip

Confirmed 1.5.4 not stuck
Where 1.5.5 is stuck 

Tried on debug build to have info print

![IMG_20201210_210205.jpg](https://user-images.githubusercontent.com/473990/101784987-3007f500-3b37-11eb-8d08-89658f12b267.jpg)

**Comment by keatliang2005** [comment] 2020-12-10 14:49
> If the cause is AppleALC, and it stuck at PCI (but mine device don't stuck),
> I guess the most likely suspicious change is here:
> https://github.com/acidanthera/AppleALC/commit/3708e1ceabe590a8ea7a13f8d0447cbaaadecb49#
> The change for key `IOProviderClass`  to value `IOHDACodecDevice`. (it's related to the HDAS->HDEF patch).
> 
> If you want to dive deep into this issue, you can use the following build (build between 1.5.4 and 1.5.5, without the above commit in `IOProviderClass`)to see if the stuck issue exists.
> https://github.com/dortania/build-repo/releases/download/AppleALC-05c055a/AppleALC-1.5.5-RELEASE.zip

Alright will test see the return result

**Comment by keatliang2005** [comment] 2020-12-11 04:55
> > If the cause is AppleALC, and it stuck at PCI (but mine device don't stuck),
> > I guess the most likely suspicious change is here:
> > https://github.com/acidanthera/AppleALC/commit/3708e1ceabe590a8ea7a13f8d0447cbaaadecb49#
> > The change for key `IOProviderClass`  to value `IOHDACodecDevice`. (it's related to the HDAS->HDEF patch).
> > 
> > If you want to dive deep into this issue, you can use the following build (build between 1.5.4 and 1.5.5, without the above commit in `IOProviderClass`)to see if the stuck issue exists.
> > https://github.com/dortania/build-repo/releases/download/AppleALC-05c055a/AppleALC-1.5.5-RELEASE.zip
> 
> Alright will test see the return result

Build from 05c055a it crash too 

Debug build
![IMG_20201211_113508.jpg](https://user-images.githubusercontent.com/473990/101864960-04752100-3bb0-11eb-818b-b75101219818.jpg)

Release build
![IMG_20201211_113924.jpg](https://user-images.githubusercontent.com/473990/101864984-0b039880-3bb0-11eb-9454-ec23fc24339b.jpg)

I think gonna try one build at a time to determine which changes cause the crash

**Comment by keatliang2005** [comment] 2020-12-12 05:20
after doing some looging and here are the interesting fragment of the log

particular last line

51:524 00:044 AAPL: #[EB|LOG:EXITBS:START] 2020-12-12T05:11:37

i have tried the steps to see any changes but no avails

https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start


```
42:786 00:039 OCB: Perform boot DARWIN to dp PciRoot(0x0)/Pci(0x1D,0x0)/Pci(0x0,0x0)/NVMe(0x1,B5-38-CF-25-28-B7-26-00)/HD(2,GPT,1688B33E-D88C-4BA9-8D85-77FB9EBAA6B5,0x64028,0x1D161920)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,FF6E62E48F0BD64C8D214E815FAFEB91)/\ED16F596-04BA-44C9-9139-7A630D285B16\System\Library\CoreServices\boot.efi (0/0)
42:828 00:042 OCSB: Secure boot is disabled, skipping
42:868 00:039 OCB: Arch filtering 772A4018(723512)->772A4018(723512) caps 4 - Success
42:917 00:048 OCB: Matching <> args on type 2 0
42:956 00:039 OCABC: VMware Mac installed on 773B5E18 - Success
42:996 00:040 OCABC: All slides are usable! You can disable ProvideCustomSlide!
43:037 00:040 AAPL: #[EB|LOG:INIT] 2020-12-12T05:11:29
43:076 00:038 AAPL: #[EB|VERSION] <"boot.efi 495.40.10~123 (Official), built 2020-10-30T00:08:36-0700">
43:116 00:040 AAPL: #[EB|BUILD] <"BUILD-INFO[302]:{"DisplayName":"boot.efi","DisplayVersion":"495.40.10~123","RecordUuid":"F4088230-E9C1-4D37-8D7A-37D28C4A4268","BuildTime":"2020-10-30T00:08:36-0700","ProjectName":"efiboot","ProductName":"boot.efi","SourceVersion":"495.40.10","BuildVersion":"123","BuildConfiguration":"Release","BuildType":"Official"}">
43:157 00:040 AAPL: #[EB|CFG:DEV] r2 0x0 0x0
43:292 00:135 AAPL: #[EB|H:IS] 0
43:332 00:039 AAPL: #[EB|WL:MODE] 0
43:372 00:040 AAPL: #[EB|CFG:ARG] boot-save-log 0x0000000000000002 (0x0000000000000002 < 0xFFFFFFFFFFFFFFFF) default
43:413 00:041 AAPL: #[EB|CFG:ARG] wake-save-log 0x0000000000000002 (0x0000000000000002 < 0x0000000000000002) default
43:453 00:039 AAPL: #[EB|CFG:ARG] console       0x0000000000000001 (0x0000000000000001 < 0x0000000000000001) default
43:494 00:040 AAPL: #[EB|CFG:ARG] serial        0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) default
43:534 00:039 AAPL: #[EB|CFG:ARG] embed-log-dt  0x0000000000000000 (0x0000000000000000 < 0x0000000000000000) default
43:574 00:040 AAPL: #[EB|CFG:ARG] timestamps    0x0000000000000000 (0x0000000000000000 < 0xFFFFFFFFFFFFFFFF) default
43:614 00:039 AAPL: #[EB|CFG:ARG] log-level     0x0000000000000001 (0x0000000000000001 & 0x0000000000000021) default
43:655 00:040 AAPL: #[EB|CFG:ARG] breakpoint    0x0000000000000000 (0x0000000000000000 & 0x0000000000000000) default
43:695 00:039 AAPL: #[EB|CFG:ARG] kc-read-size  0x0000000000100000 (0x0000000000100000 < 0xFFFFFFFFFFFFFFFF) default
43:735 00:040 AAPL: #[EB|H:IS] 0
43:775 00:040 AAPL: #[EB|WL] 0 0 0x01 0x01   0 0x00
43:815 00:039 AAPL: #[EB|BRD:NV] Mac-7BA5B2DFE22DDD8C
43:855 00:040 OCOS: OS set: <null> macOS 11.0
43:894 00:038 OCOS: OS set: Apple Inc. macOS 11.0
43:934 00:039 AAPL: #[EB|WL] 0 0 0x01 0x01   2 0x00
44:068 00:134 AAPL: #[EB.BST.IDT|+]
44:110 00:042 AAPL: #[EB.BST.IDT|-]
44:151 00:040 AAPL: #[EB|WL] 0 0 0x01 0x01   3 0x00
44:190 00:039 AAPL: #[EB|WL] 0 0 0x01 0x01   4 0x00
44:231 00:040 AAPL: #[EB|BRD:NV] Mac-7BA5B2DFE22DDD8C
44:270 00:039 AAPL: #[EB|WL] 0 0 0x01 0x01   5 0x00
44:311 00:040 AAPL: #[EB.H.CHK|BM] 0x0000000000000000
44:350 00:039 AAPL: #[EB.H.LV|!] Err(0xE) <- RT.GV boot-signature 7C436110-AB2A-4BBB-A880-FE41995C9F82
44:391 00:040 AAPL: #[EB|WL] 0 0 0x01 0x01  23 0x0E
44:430 00:039 AAPL: #[EB.H.LV|!] Err(0xE) <- RT.GV boot-image-key 7C436110-AB2A-4BBB-A880-FE41995C9F82
44:471 00:040 AAPL: #[EB|WL] 0 0 0x01 0x01  24 0x0E
44:511 00:040 AAPL: #[EB.H.LV|!] Err(0xE) <- RT.GV boot-image 7C436110-AB2A-4BBB-A880-FE41995C9F82
44:550 00:039 AAPL: #[EB.H.LV|!] Err(0xE) <- RT.SV- boot-signature 7C436110-AB2A-4BBB-A880-FE41995C9F82
44:591 00:040 AAPL: #[EB.H.LV|!] Err(0xE) <- RT.SV- boot-image-key 7C436110-AB2A-4BBB-A880-FE41995C9F82
44:630 00:038 AAPL: #[EB.H.LV|!] Err(0xE) <- RT.SV- boot-image 7C436110-AB2A-4BBB-A880-FE41995C9F82
44:670 00:040 AAPL: #[EB|H:NOT]
44:709 00:039 AAPL: #[EB|SB:P] 0x0
44:959 00:249 AAPL: #[EB|LIMG:DP] Acpi(PNP0A03,0)/Pci(1D|0)/Pci(0|0)/?[ 0x83 0x17 0x10 0x0 0x1 0x0 0x0 0x0 0x0 0x26 0xB7 0x28 0x25 0xCF 0x38 0xB5 ]/HD(Part2,Sig1688B33E-D88C-4BA9-8D85-77FB9EBAA6B5)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842)
45:000 00:041 AAPL: #[EB|LIMG:FP] \ED16F596-04BA-44C9-9139-7A630D285B16\System\Library\CoreServices\boot.efi
45:040 00:039 AAPL: #[EB|LIMG:OPT] 
45:080 00:040 AAPL: #[EB.OPT.LXF|F] <"\\ED16F596-04BA-44C9-9139-7A630D285B16\\System\\Library\\CoreServices\\com.apple.Boot.plist">
45:120 00:039 AAPL: #[EB.LD.LF|IN] 0 1 <"\\ED16F596-04BA-44C9-9139-7A630D285B16\\System\\Library\\CoreServices\\com.apple.Boot.plist"> <"0">
45:161 00:040 AAPL: #[EB.LD.OFS|OPEN!] Err(0xE) <"\\ED16F596-04BA-44C9-9139-7A630D285B16\\System\\Library\\CoreServices\\com.apple.Boot.plist">
45:200 00:039 AAPL: #[EB.OPT.LXF|LF!] Err(0xE)
45:240 00:040 AAPL: #[EB.OPT.LXF|F] <"Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist">
45:280 00:039 AAPL: #[EB.LD.LF|IN] 0 1 <"Library\\Preferences\\SystemConfiguration\\com.apple.Boot.plist"> <"0">
45:320 00:040 AAPL: #[EB|KF] <"">
45:361 00:040 AAPL: #[EB|MBA:CL] <"">
45:489 00:127 AAPL: #[EB|MBA:NV] <"alcid=11 agdpmod=ignore -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 igfxmetal=1 -v">
45:533 00:044 AAPL: #[EB|MBA:KF] <"">
45:572 00:038 AAPL: #[EB|MBA:OUT] <"alcid=11 agdpmod=ignore -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 igfxmetal=1 -v">
45:613 00:040 AAPL: #[EB|LOG:VERBOSE] 2020-12-12T05:11:31
45:652 00:039 AAPL: #[EB|OPT:BM] 0x80102
45:692 00:039 AAPL: #[EB.OPT.LXF|F] <"\\ED16F596-04BA-44C9-9139-7A630D285B16\\System\\Library\\CoreServices\\PlatformSupport.plist">
45:826 00:134 AAPL: #[EB.LD.LF|IN] 0 1 <"\\ED16F596-04BA-44C9-9139-7A630D285B16\\System\\Library\\CoreServices\\PlatformSupport.plist"> <"0">
45:869 00:042 AAPL: #[EB|B:VAw]
45:910 00:040 AAPL: #[EB|P:CPR] N
45:949 00:039 AAPL: #[EB|P:MPI] N
45:990 00:040 AAPL: #[EB|P:BPI] N
46:029 00:039 AAPL: #[EB|KMR] 499802112
46:070 00:040 AAPL: #[EB.CS.CSKSD|+]
46:109 00:039 AAPL: #[EB.CS.CSKSD|!] Err(0xE) <- RT.GV boot-info-payload 8D63D4FE-BD3C-4AAD-881D-86FD974BC1DF
46:150 00:040 AAPL: #[EB|WL] 0 0 0x01 0x01   6 0x0E
46:190 00:040 AAPL: #[EB.CS.LFC|+]
46:230 00:039 AAPL: #[EB.LD.LF|IN] 0 1 <"System\\Library\\Caches\\com.apple.corestorage\\EncryptedRoot.plist.wipekey"> <"0">
46:272 00:042 AAPL: #[EB.FS.AGSVH|PU] ED16F596-04BA-44C9-9139-7A630D285B16
46:312 00:039 AAPL: #[EB.FS.AGSVH|!] Err(0xE) <- BS.LocHB 59D76AE4-37E3-55A7-B460-EF13D46E6020
46:352 00:040 AAPL: #[EB.G.CS|-?] Ok(0)
46:395 00:042 AAPL: #[EB.LD.LF|IN] 0 1 <"<null string>"> <"1">
46:438 00:042 AAPL: #[EB.B.SBS|SZ] 723512
46:487 00:049 AAPL: #[EB|B:SHA] <ea50cabcff030287cd7710d924d21389146845bc>
46:562 00:075 AAPL: #[EB.WL.PWLFNV|!] Err(0xE) <- RT.GV wake-failure 7C436110-AB2A-4BBB-A880-FE41995C9F82
46:673 00:110 AAPL: #[EB.WL.DT|!] Err(0xE) <- EB.WL.PWLFNV
46:715 00:041 AAPL: #[EB|WL:DT] 0x3fe3be82
46:764 00:048 AAPL: #[EB.LD.LKC|D] <"boot\System\Library\KernelCollections\BootKernelExtensions.kc.development">
46:814 00:050 AAPL: #[EB.LD.OFS|OPEN!] Err(0xE) <"boot\\System\\Library\\KernelCollections\\BootKernelExtensions.kc.development">
46:862 00:048 AAPL: #[EB.LD.LKC|R.2] <"boot\System\Library\KernelCollections\BootKernelExtensions.kc">
47:246 00:383 OC: Kext reservation size info 560000 exe 1C37000
47:291 00:045 OC: Trying 64-bit XNU hook on boot\System\Library\KernelCollections\BootKernelExtensions.kc
47:358 00:066 OC: Result of 64-bit XNU hook on boot\System\Library\KernelCollections\BootKernelExtensions.kc (00000000) is Success
47:408 00:050 OCAK: Read kernel version 20.1.0 (200100)
47:452 00:043 OCAK: Replacing _xcpm_core_scope_msrs data 226 76
47:491 00:039 OCAK: Replacing _xcpm_core_scope_msrs data 226 406416
47:531 00:040 OCAK: Replacing _xcpm_core_scope_msrs data 226 16384
47:571 00:039 OCAK: Not matching _xcpm_core_scope_msrs data 46 422876
47:613 00:042 OCAK: 64-bit XcpmCfgLockRel replace count - 2
47:676 00:062 OCAK: 64-bit PanicKextDump replace count - 1
47:715 00:039 OCAK: Patch success kext dump
47:856 00:141 OCAK: Local relocs 784 on FFFFFF8003FA8000
47:993 00:136 OC: Prelinked injection Lilu.kext () - Success
48:037 00:043 OCAK: Patching invalid size 2000 with 18D6000 for com.apple.iokit.IOACPIFamily
48:089 00:052 OCAK: Local relocs 503 on FFFFFF800402E000
48:133 00:043 OC: Prelinked injection VirtualSMC.kext () - Success
48:183 00:049 OCAK: Patching invalid size 28000 with 1391000 for com.apple.iokit.IOPCIFamily
48:242 00:059 OCAK: Local relocs 5252 on FFFFFF8004048000
48:319 00:076 OC: Prelinked injection AppleALC.kext () - Success
48:361 00:041 OCAK: Patching invalid size 10000 with 18D0000 for com.apple.iokit.IOAHCIFamily
48:426 00:065 OCAK: Local relocs 2526 on FFFFFF80041CA000
48:477 00:050 OC: Prelinked injection CtlnaAHCIPort.kext () - Success
48:524 00:046 OCAK: Patching invalid size 8D000 with 105F000 for com.apple.iokit.IOUSBHostFamily
48:563 00:039 OCAK: Patching invalid size 4000 with 2A21000 for com.apple.driver.AppleBusPowerController
48:605 00:041 OCAK: Patching invalid size 19000 with 2718000 for com.apple.driver.AppleSMC
48:649 00:044 OCAK: Patching invalid size 2000 with A56000 for com.apple.driver.watchdog
48:694 00:044 OCAK: Patching invalid size 4000 with 25CC000 for com.apple.driver.usb.AppleUSBCommon
48:739 00:045 OCAK: Dependency com.apple.driver.usb.AppleUSBHostPlatformProperties was not found for kext com.apple.iokit.IOUSBHostFamily
48:807 00:067 OCAK: Local relocs 368 on FFFFFF80041F2000
48:943 00:136 OC: Prelinked injection IntelBluetoothFirmware.kext () - Success
48:983 00:039 OCAK: Local relocs 2 on FFFFFF80050BE000
49:024 00:040 OC: Prelinked injection IntelBluetoothInjector.kext () - Success
49:067 00:042 OCAK: Patching invalid size 17000 with 161A000 for com.apple.iokit.IONetworkingFamily
49:128 00:061 OCAK: Local relocs 628 on FFFFFF80050C1000
49:171 00:042 OC: Prelinked injection IntelMausi.kext () - Success
49:246 00:075 OCAK: Local relocs 2067 on FFFFFF80050EA000
49:294 00:047 OC: Prelinked injection itlwm.kext () - Success
49:342 00:047 OCAK: Local relocs 323 on FFFFFF8005B11000
49:383 00:041 OC: Prelinked injection Polaris22Fixup.kext () - Success
49:439 00:055 OCAK: Local relocs 782 on FFFFFF8005B20000
49:575 00:136 OC: Prelinked injection SmallTreeIntel82576.kext () - Success
49:626 00:050 OCAK: Local relocs 332 on FFFFFF8005B4E000
49:667 00:040 OC: Prelinked injection SMCProcessor.kext () - Success
49:715 00:048 OCAK: Local relocs 300 on FFFFFF8005B5D000
49:755 00:040 OC: Prelinked injection USBWakeFixup.kext () - Success
49:807 00:051 OCAK: Local relocs 1591 on FFFFFF8005B65000
49:948 00:140 OC: Prelinked injection WhateverGreen.kext () - Success
49:990 00:041 OC: Prelink size 94892032 kext offset 65306624 reserved 29585408
50:030 00:039 OCAK: KC TEXT is 65536 bytes with 50560 Mach-O headers need 1032
50:106 00:075 OCAK: Patching invalid size 1E000 with 28B6000 for com.apple.driver.AppleIntelCPUPowerManagement
50:195 00:089 OCAK: 64-bit AppleIoMapper replace count - 1
50:235 00:039 OCAK: Patch success com.apple.iokit.IOPCIFamily AppleIoMapper
50:433 00:198 OC: Prelinked status - Success
50:489 00:056 AAPL: #[EB.LD.LKFS|-?] Ok(0)
50:532 00:042 AAPL: #[EB.LD.LKC|-?] Ok(0)
50:574 00:042 AAPL: #[EB|FWFM] 0x00000000FFDFFF7F
50:617 00:042 AAPL: #[EB|FWFT] 0x00000000FD8FF466
50:659 00:041 AAPL: #[EB|BST:REV1]
50:698 00:039 OCABC: GetVariable csr-active-config - Not Found
50:741 00:042 AAPL: #[EB|CSR:IN] 0x00000040
50:782 00:041 AAPL: #[EB|CSR:OUT] 0x00000040
50:823 00:041 AAPL: #[EB.BST.FBS|+]
50:864 00:040 AAPL: #[EB.BST.FBS|ADSZ] 0
50:999 00:134 AAPL: #[EB.BST.FBS|KSSZ] 0
51:044 00:044 AAPL: #[EB|SB:SBGMFNS] x86legacyap.im4m
51:088 00:044 AAPL: #[EB|RH:PF] usr\standalone\OS.dmg.root_hash
51:135 00:046 AAPL: #[EB|RH:MF] <"usr\\standalone\\OS.dmg.root_hash.x86legacyap.im4m">
51:181 00:045 AAPL: #[EB.LD.LF|IN] 0 1 <"usr\\standalone\\OS.dmg.root_hash"> <"0">
51:229 00:048 AAPL: #[EB.LD.LF|IN] 0 1 <"usr\\standalone\\OS.dmg.root_hash.x86legacyap.im4m"> <"0">
51:271 00:041 AAPL: #[EB.BST.FBS|RHPSZ] 229
51:314 00:042 AAPL: #[EB.BST.FBS|RHMSZ] 3627
51:354 00:039 OCSMC: SmcReadValue Key 4D535463 Size 1
51:394 00:040 OCSMC: SmcReadValue Key 4D534163 Size 2
51:437 00:042 AAPL: #[EB.B.WFDW|!WF] Err(0xE) 0
51:479 00:042 AAPL: #[EB|LOG:DT] 2020-12-12T05:11:37
51:524 00:044 AAPL: #[EB|LOG:EXITBS:START] 2020-12-12T05:11:37
```

**Comment by goodbest** [comment] 2020-12-13 15:38
@keatliang2005 
You can try the latest build https://github.com/acidanthera/bugtracker/issues/1360#issuecomment-744021277

The kexts can be found here:
https://github.com/dortania/build-repo/releases/tag/AppleALC-f73b904

**Comment by keatliang2005** [comment] 2020-12-13 15:51
Tried it still stall at PCI configuration

However this build seems have more info

```
Lilu nvram :@ fail to get IODeviceTree:/options
```

![IMG_20201213_234816.jpg](https://user-images.githubusercontent.com/473990/102016811-d0f7e980-3d9d-11eb-9c73-48d12a692af1.jpg)

**Comment by keatliang2005** [comment] 2020-12-14 07:01
After having pointer from @vit9696, turns out there is a missing quirks key at kernel DisableLinkeditJettison are part of Big Sur requirement.

[config.plist.zip](https://github.com/osy/HaC-Mini/files/5686998/config.plist.zip), hope this makes it into next release of Hac-Mini :)

hence the config.plist have many missing quirks key across Booter, Kernel and UEFI

So i suggest fill all the required quirks, i look liberty to do the filling. after referring to OC 0.64 sample and guide from (assumed Kady Lake-G is identical to Laptop Kaby Lake). i already fill all the value suggested in the guide below, and leave the original Hac-Mini value intact.

https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html
https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#booter
https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#kernel
https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#uefi
https://dortania.github.io/docs/latest/Configuration.html

**Comment by keatliang2005** [comment] 2020-12-17 03:56
@Xuemuyang can you test this build based on v2.15 ?

https://github.com/osy/HaC-Mini/suites/1676740191/artifacts/31328446

**Comment by osy** [comment] 2020-12-28 02:01
Fixed by #470, will add missing quarks in the future after more research and testing.

**Closed by osy** 2020-12-28 02:01 UTC
Labels: bug

**Comment by osy86** [comment] 2021-02-11 12:36
MIECRAFT!!1111
