### ISSUE TITLE
Flashes when the screen wakes up.

### ISSUE THREAD

**Issue by redblue9771** [osy/HaC-Mini#543] opened 2021-03-04 08:53 UTC
**Describe the bug**
Flashes when the screen wakes up.

**Expected behavior**
Normal display.

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.16
- OSX version [e.g: 10.14.6]: 11.2
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: WDC WDS100T2B0C 1TB
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Kingston DDR4-2667 16G
- Second DIMM model (if installed):  Kingston DDR4-2667 16G
- Display port(s) used [e.g: USB-C, mini DP]: Type-C
- Display resolution(s) [e.g: 4K, 5K]: 4K (Dell U2720QM)
- Any TB3 devices: 
- Any USB devices: 
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: BCM20702B0

Switching the resolution can temporarily solve the problem.

**Comment by osy** [comment] 2021-03-04 20:15
Duplicate of #7

**Closed by osy** 2021-03-04 20:15 UTC
Labels: duplicate
