### ISSUE TITLE
Improve the performance of the graphics card, delete the core display ID, optimize the DSDT error.

### ISSUE THREAD

**Issue by a13302211596** [osy/HaC-Mini#295] opened 2020-07-15 16:58 UTC
Performance test of video card
<img width="976" alt="53F76DEBCEDEBABB0C2FDD9C35EFF548" src="https://user-images.githubusercontent.com/53515825/87572559-4fbcfd80-c6fe-11ea-9282-6d01c7a48c37.png">
<img width="976" alt="1735BF5598F8F39AB5D97440B07D67E1" src="https://user-images.githubusercontent.com/53515825/87572579-577ca200-c6fe-11ea-87c0-a5450d3ef85e.png">

Performance comparison with mbp16 inch

Increased drive
<img width="770" alt="9BEE4C42-78E0-42A4-8DCD-7298A60DC9C0" src="https://user-images.githubusercontent.com/53515825/87572973-e2f63300-c6fe-11ea-9370-15bd5fb370e5.png">
<img width="1279" alt="57CE1596-1F93-4CFD-953E-906B7602FD18" src="https://user-images.githubusercontent.com/53515825/87572987-e7225080-c6fe-11ea-898f-2e78d97301fb.png">

DSDT status and added options
<img width="960" alt="EE16541A-EED0-4B30-ACC1-7C6BAB95C393" src="https://user-images.githubusercontent.com/53515825/87573053-04efb580-c6ff-11ea-81c8-9b9754e12d64.png">

EFI package sharing
[EFI-OC-7.16.zip](https://github.com/osy86/HaC-Mini/files/4926644/EFI-OC-7.16.zip)

Source file from HAC mini, thanks for osy86's contribution, this is my QQ group 943399633, welcome to join

**Comment by a13302211596** [comment] 2020-07-15 17:05
Performance comparison with mbp16 inch
<img width="960" alt="180510243A170A74461D4D1B8DD736DC" src="https://user-images.githubusercontent.com/53515825/87573986-4a60b280-c700-11ea-8034-1461a9fb4335.png">

**Comment by a13302211596** [comment] 2020-07-15 17:06
<img width="640" alt="1" src="https://user-images.githubusercontent.com/53515825/87574104-7c721480-c700-11ea-87c0-50569944f48c.png">

**Comment by osy86** [comment] 2020-07-15 17:35
DSDT patches for _OSI and _DSM are bad and can break things in Windows as well as wakeup/bios features. Not recommended. It won’t make a difference in performance. 

Not sure what the other changes are. I don’t really understand from the screenshots.

**Comment by a13302211596** [comment] 2020-07-15 17:56
> DSDT patches for _OSI and _DSM are bad and can break things in Windows as well as wakeup/bios features. Not recommended. It won’t make a difference in performance.
> 
> Not sure what the other changes are. I don’t really understand from the screenshots.

Performance improvement of graphics card

**Comment by a13302211596** [comment] 2020-07-15 18:02
@osy86 RadeonBoost.kext，Improve the graphics card performance.

**Comment by osy86** [comment] 2020-07-15 20:13
I don't understand your results (which is before and after? why is there four screenshots?) Here's my own tests with RadeonBoost.kext

Geekbench 5.2.2 Metal - AMD - No RadeonBoost - 27336
Geekbench 5.2.2 OpenCL - AMD - No RadeonBoost - 25552
Geekbench 5.2.2 Metal - AMD - RadeonBoost - 28898
Geekbench 5.2.2 OpenCL - AMD - RadeonBoost - 27911

I'm not getting 32153 or 94691

**Comment by candyrock** [comment] 2020-07-15 22:13
> I don't understand your results (which is before and after? why is there four screenshots?) Here's my own tests with RadeonBoost.kext
> 
> Geekbench 5.2.2 Metal - AMD - No RadeonBoost - 27336
> Geekbench 5.2.2 OpenCL - AMD - No RadeonBoost - 25552
> Geekbench 5.2.2 Metal - AMD - RadeonBoost - 28898
> Geekbench 5.2.2 OpenCL - AMD - RadeonBoost - 27911
> 
> I'm not getting 32153 or 94691

Yeah. The Radeonboost doesn't improve scores. Apple have changed driver since catalina.

**Comment by osy86** [comment] 2020-07-15 22:16
Then I’m not sure what OP’s screenshots are about.

**Comment by a13302211596** [comment] 2020-07-16 01:10
@osy86 Known Issues
Lower GeekBench score (#286) Unfortunately this is due to Apple's latest AMD drivers registering a lower score than other ones. You can manually install with the instructions in #286 but it may stop working in macOS 11.OldRadeonX4000HWLibs.kext
<img width="770" alt="(MOZ$93XFM9)A0F9(_SCYWN" src="https://user-images.githubusercontent.com/53515825/87614933-042d4280-c744-11ea-8cb5-2baeec392780.png">
<img width="976" alt="D_O~5MQ6E~50YKY )PQ(R31" src="https://user-images.githubusercontent.com/53515825/87614946-0c857d80-c744-11ea-90de-c58f36238ebd.png">
<img width="976" alt="MG8$D_`CWBNZ RHZHDQ8CMS" src="https://user-images.githubusercontent.com/53515825/87614950-0db6aa80-c744-11ea-832c-f545c94e213e.png">
This is not used with the oldradon X4000 HWLibs.kext test result
4K resolution

**Comment by osy86** [comment] 2020-07-16 01:12
Okay then if the score is due to the new RadeonX4000 kext and RadeonBoost doesn’t improve the scores, there’s nothing to do here?

**Comment by a13302211596** [comment] 2020-07-16 01:22
@osy86 Test system version MAC os10.15.5

**Comment by a13302211596** [comment] 2020-07-16 01:30
![FKI_ @{6O_6 7928})5ITT1](https://user-images.githubusercontent.com/53515825/87616115-f1683d00-c746-11ea-8da4-cca47b9ec24d.png)

**Comment by slimx** [comment] 2020-07-16 02:00
如果用了2.1可以通过这个kext来提升性能。如果是2.09和之前的就不必用了？

**Comment by a13302211596** [comment] 2020-07-16 02:07
我使用的是HaC-Mini v2.10

**Comment by slimx** [comment] 2020-07-16 03:25
2.09 without boost kext, metal is 30000
2.10 with boost kext, metal is 32000

**Comment by osy86** [comment] 2020-07-16 03:31
I am not able to reproduce this. I used the EFI.zip from the attachment for my tests and got 28898

**Comment by a13302211596** [comment] 2020-07-16 03:40
@osy86 2.10 10.15.5、4K resolution、with boost kext, metal is 32000

**Comment by a13302211596** [comment] 2020-07-16 03:44
If the EFI I uploaded is a dual system boot, press the ALT button continuously to select Mac OS

**Comment by osy86** [comment] 2020-07-16 03:57
It does not work for me.  I will wait for someone else to test it.

**Comment by goodbest** [comment] 2020-07-16 10:22
I haven't test RadeonBoost, But I have found something before.

With Hac Mini 2.10, 
you will get 26000~28000 with AMD decoding options.
Meanwhile, if you manully remove the shikid and shigigva in nvram, then you wil get ~31000.

**Comment by osy** [comment] 2020-12-28 02:02
Closing since this is outdated.

**Closed by osy** 2020-12-28 02:02 UTC
Labels: graphics
