### ISSUE TITLE
ESP bug of installer

### ISSUE THREAD

**Issue by JerryXu-code** [osy/HaC-Mini#534] opened 2021-01-26 09:20 UTC
- Running OSX version: 11.1
 - Target drive OSX version: 11.1
 - HaC Mini installer version: v2.7 to v2.16(maybe)
 There's a bug with the installer.I tried to install HaC-Mini v2.16,but it failed.The log says : can't mount ESP partition (disk0s1) !
but my ESP partition is disk0s5,so this is weird.I also tried to install v2.7,but still this problem.
Maybe this bug is because of Bug sur👍  because i can install v2.7 when i'm using 10.15
Here's the full log:
[log.txt](https://github.com/osy/HaC-Mini/files/5872381/log.txt)

**Comment by osy** [comment] 2021-01-26 09:24
Duplicate of #533

**Closed by osy** 2021-01-26 09:24 UTC
Labels: duplicate
