### ISSUE TITLE
Screen that uses scaled resolution glitches after waking up

### ISSUE THREAD

**Issue by geekdada** [osy/HaC-Mini#464] opened 2020-12-09 14:56 UTC
**Describe the bug**
This issue is not a duplication of #277.

The screen would be just fine waking up if it sticks to the default resolution (1920x1080 HiDPI), but it glitches after waking up if the resolution is scaled.

Setting the resolution to default, the screen would become normal.

**Configuration**
- HaC Mini version [e.g: 2.0]: v2.15
- OSX version [e.g: 10.14.6]: 11.0.1
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: 
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: USB-C to HDMI
- Display resolution(s) [e.g: 4K, 5K]: 2560x1440 HiDPI
- Any TB3 devices: 
- Any USB devices: 
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]:

**Comment by geekdada** [comment] 2020-12-09 14:59
I'm not sure how it behaved before v2.15, I just started using scaled resolution today.

**Comment by osy** [comment] 2020-12-09 15:38
Did you install the reduce flickering workaround in the installer?

**Comment by geekdada** [comment] 2020-12-09 15:55
Wow, it's working like a charm!

Thanks!

**Comment by osy** [comment] 2020-12-09 15:58
Duplicate of #7

**Closed by osy** 2020-12-09 15:58 UTC
Labels: graphics

**Comment by geekdada** [comment] 2020-12-09 16:03
Oh, I take my words back.

The screen continues to flicker when I switch from space to space, sleep then wake up doesn't make any difference.

I should probably go back to normal resolution.

Thanks anyway!
